### PR TITLE
Fix/sl-verification

### LINKED ISSUE #331: Different errors for status checks
Would be great to have different errors for JWT issues caused by statuslist checks.

Just spent days banging my head against the wall trying to figure out why a credential signature was invalid when in fact it was caused by the statuslist JWT signature.

### PR DESCRIPTION
**Pull request by cre8**
Fixes #331

- throws an error when status list validation fails. If a custom error message should be thrown, the verify funcation has to be overriden
Signed-off-by: Mirko Mollik <mirko.mollik@eudi.sprind.org>

### CODE REVIEW

**Comment by cre8** [comment]
@charsleysa please have a look if this approach is fine for you

File: packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts [hunk 1]
```diff
@@ -306,17 +306,47 @@ export class SDJwtVcInstance extends SDJwtInstance<SdJwtVcPayload> {
...
+        ) {
+          throw new SDJWTException('Verify Error: Status list is expired');
+        }
+        if (
+          slJWT.payload?.iat &&
+          (slJWT.payload.iat as number) - (options?.skewSeconds ?? 0) >
+            currentDate
+        ) {
+          throw new SDJWTException(
+            'Verify Error: Status list is not yet valid',
```
Comment (lukasjhan) [inline packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts]: Maybe we could mention which property throw an error. something like: "iat in Status list is not yet valid"

**Comment by cre8** [comment]
Oh you are right (no work without coffee in the morning), I removed also the redundant exp check.

Instead of the first fix, I appended all error messages during the verify function so it is clear when the sl jwt fails, it is clear from the error message.

**Comment by cre8** [comment]
> That would work. Though one downside is that it would suppress custom errors (you wouldn't be able to use instanceof checks).
> 
> Maybe it's better for the status list not to use the jwt verify at all and instead have it's own independent implementation.

this would end up in code duplication that I want to avoid. We may define a new Exception type like SLException?

**Comment by charsleysa** [comment]
> this would end up in code duplication that I want to avoid. We may define a new Exception type like SLException?

That would still result in the suppression of custom errors from the user supplied verifier function. Though it does help in identifying exactly status list specific errors.

My thinking is the best way to avoid duplication would be to have check helper functions which return boolean results which can then be used from the status list verify function and it is the responsibility of the status list verify function to throw the errors.

**Review by lukasjhan — COMMENTED** [review]
Looks good to me, Thanks.
Could you fix the lint error plz?

**Comment by charsleysa** [comment]
> the sdjwtexception and slexception allow to pass a message and also an object. This object is passed so no information except the type of exception is lost

Ah, so the expectation is for users to throw SDJWTException or SLException instead of their own error class so that information can be correctly propagated?

**Review by charsleysa — APPROVED** [review]
Looks good!

File: packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts [hunk 2]
```diff
@@ -306,18 +307,18 @@ export class SDJwtVcInstance extends SDJwtInstance<SdJwtVcPayload> {
...
-        if (slJWT.payload?.exp && (slJWT.payload.exp as number) < currentDate) {
-          throw new SDJWTException('Status list is expired');
-        }
+        await slJWT
+          .verify(
+            this.userConfig.statusVerifier ??
+              (this.userConfig.verifier as Verifier),
+            options,
+          )
+          .catch((err: SLException) => {
```
Comment (TimoGlastra) [inline packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts]: I think casting this as an `SLException` is unsafe, since the method could throw other errors as well (since a custom `statusVerifier` can be passed).
